config/routes.rb
Rails.application.routes.draw do
  get 'bankin/connect'
  get 'bankin/callback'

  devise_for :users


  root to: "pages#home"
  get 'expenses_summary', to: 'pages#expenses_summary'

  resources :revenues do
    resources :categories, only: [:new, :create], defaults: { category_type: 'revenue' }
  end

  resources :expenses, except: [:show]do
    resources :categories, only: [:new, :create], defaults: { category_type: 'expense' }
  end

  resources :categories, only: [:index, :new, :create, :edit, :update, :destroy]

  resources :goals do
    post 'add_money', on: :member
  end

  resources :predictions

  resources :budgets, only: [:index, :new, :create, :edit, :update, :destroy]

  resources :reconciliations, only: [:index, :new, :create, :show, :destroy] do
    post :validate_match, on: :member
  end
  get "bankin/connect", to: "bankin#connect"
  get "bankin/callback", to: "bankin#callback"



  # Health check
  get "up" => "rails/health#show", as: :rails_health_check
end

app/views/layouts/_navbar.html.erb
<!-- Checkbox pour le toggle du menu -->
<input type="checkbox" id="menu-toggle" class="menu-toggle" hidden>

<!-- Top Navbar -->
<nav class="top-navbar">
  <div class="nav-left">
    <!-- Bouton menu -->
    <label for="menu-toggle" class="menu-btn">☰</label>
  </div>

  <div class="nav-center">
    <!-- Titre / lien vers la home page -->
    <%= link_to "Économint", root_path, class: "sidebar-title" %>
  </div>

  <div class="nav-right">
    <% if user_signed_in? %>
      <div class="user-dropdown">
        <span class="nav-user">Bonjour, <%= current_user.username %></span>
        <ul class="dropdown-menu">
          <li><%= link_to "Profil", edit_user_registration_path %></li>
          <li>
            <%= link_to "Déconnexion", destroy_user_session_path,
                        method: :delete,
                        data: { turbo_method: :delete, confirm: "Voulez-vous vraiment vous déconnecter ?" } %>
          </li>
        </ul>
      </div>
    <% else %>
      <%= link_to "Connexion", new_user_session_path, class: "nav-user" %>
      <%= link_to "Inscription", new_user_registration_path, class: "nav-user" %>
    <% end %>
  </div>
</nav>

<!-- Sidebar -->
<div class="sidebar">
  <ul class="sidebar-links">
    <li><%= link_to "Dépenses", expenses_path %></li>
    <li><%= link_to "Trésorerie", revenues_path %></li>
    <li><%= link_to "Épargne", goals_path %></li>
    <li><%= link_to "Prédiction", predictions_path %></li>
    <li><%= link_to "Budgets", budgets_path %></li>
    <li><%= link_to "Reconciliations", reconciliations_path %></li>

  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Economint</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/chartkick@4.1.1/dist/chartkick.min.js" defer></script>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" integrity="sha512-v4..." crossorigin="anonymous" referrerpolicy="no-referrer" />



  </head>

  <body>
    <%= render "layouts/navbar" %>
    <div id="flash">
      <%= render "shared/flash" %>
    </div>

    <main>
      <%= yield %>
    </main>
  </body>
</html>

app/views/layouts/flash.turbo_stream.erb
<%= turbo_stream.replace "flash" do %>
  <%= render "shared/flash" %>
<% end %>